name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo

      - name: Build Sphinx docs
        run: |
          cd ./docs/ 
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PR }}
          publish_dir: ./docs/_build/html/  # Adjust this to point to your Sphinx build output directory

